CREATE DATABASE STUDENTINFORMATIONSYSTEM

USE STUDENTINFORMATIONSYSTEM

CREATE TABLE SUBJECTTABLE(SUBJECTID INT PRIMARY KEY, SUBJECTNAME VARCHAR(65), COURSE VARCHAR(15), SEM INT,CREDIT INT)

CREATE TABLE MAINTABLE(REGNO VARCHAR(10) PRIMARY KEY, STUDENTNAME VARCHAR(35), COURSE VARCHAR(15) , YEAROFSTUDY INT)

CREATE TABLE PERSONALTABLE(REGNO VARCHAR(10) PRIMARY KEY, STUDENTNAME VARCHAR(35) , YEAROFSTUDY INT,
COURSE VARCHAR(15), SEX VARCHAR(6), RELIGION VARCHAR(15), CASTE VARCHAR(15), BLOOD VARCHAR(3), INCOME REAL,DOB DATE,STUDENTADDRESS VARCHAR(80), PH VARCHAR(13),PICPATH VARCHAR(150)) 

CREATE TABLE FAMILYTABLE(REGNO VARCHAR(10) PRIMARY KEY, FATHERNAME VARCHAR(35), FATHEROCCUPATION VARCHAR(20), FATHERADDRESS VARCHAR(60), MOTHERNAME VARCHAR(35), MOTHEROCCUPATION VARCHAR(20), 
FATHERPH VARCHAR(13), GUARDIANNAME VARCHAR(35),GUARDIANADDRESS VARCHAR(60), GUARDIANPH VARCHAR(13),BROSIS VARCHAR(100)) 

CREATE TABLE EXAMTABLE(REGNO VARCHAR(10), EXAMNO INT PRIMARY KEY, COURSE VARCHAR(6) , YEAROFPASSING INT ,
INSTITUTIONNAME VARCHAR(30) , GRADE CHAR(2), PERCENTAGE REAL,NOOFCHANCE INT)
 
CREATE TABLE PHYSICALTABLE(REGNO VARCHAR(10) PRIMARY KEY, CATEGORY VARCHAR(25), SUBCATEGORY VARCHAR(25),POSITION VARCHAR(20))

CREATE TABLE INTERNALMARKTABLE(MARKID VARCHAR(10), REGNO VARCHAR(10) , SEM INT, COURSE VARCHAR(15), SUBJECTNAME  VARCHAR(65), TEST1 INT, TEST2 INT, ATTENDANCE INT,
SEMINAR INT, INTERNALMARK INT) 

CREATE TABLE LOGINTABLE(USERNAME VARCHAR(20) PRIMARY KEY,PWD VARCHAR(20),HINT VARCHAR(40))

CREATE TABLE TEMPTABLE(TNO INT PRIMARY KEY,TOTALMARK INT)

CREATE TABLE ADMINOPTIONS(SISDATE DATE, MARK INT)

CREATE TABLE SEARCHENGINE(QNO INT,SPROCEDURE VARCHAR(100),QUESTION VARCHAR(100))

CREATE TABLE PROGRAMME(NAME VARCHAR(20))

CREATE TABLE RELIGION(NAME VARCHAR(20))

CREATE TABLE CASTE(NAME VARCHAR(20))

CREATE TABLE SCHOOL(NAME VARCHAR(40))

CREATE TABLE SISSTEEINGS(MAXMARK INT,ADDITMARK INT)

CREATE TABLE ATTACHMENTTABLE(REGNO VARCHAR(10),PICPATH VARCHAR(150))

SELECT * FROM SUBJECTTABLE
SELECT * FROM MAINTABLE 
SELECT * FROM PERSONALTABLE 
SELECT * FROM FAMILYTABLE
SELECT * FROM EXAMTABLE
SELECT * FROM PHYSICALTABLE
SELECT * FROM INTERNALMARKTABLE

SELECT * FROM LOGINTABLE

SELECT * FROM PROGRAMME 
SELECT * FROM RELIGION 
SELECT * FROM CASTE 
SELECT * FROM SCHOOL 

DROP TABLE PERSONALTABLE
DROP TABLE INTERNALMARKTABLE
DROP TABLE MAINTABLE
DROP TABLE SUBJECTTABLE
DROP TABLE LOGINTABLE
DROP TABLE FAMILYTABLE
DROP TABLE TEMPTABLE
DROP TABLE INTERNALMARKTABLE
DROP TABLE EXAMTABLE
DROP TABLE PHYSICALTABLE
DROP TABLE SEARCHENGINE
DROP TABLE PROGRAMME
DROP TABLE RELIGION
DROP TABLE CASTE
DROP TABLE SCHOOL
DROP TABLE ATTACHMENTTABLE

DELETE EXAMTABLE WHERE GRADE=''
SELECT * FROM EXAMTABLE
SELECT * FROM LOGINTABLE
SELECT * FROM MAINTABLE WHERE REGNO ='12119744'
SELECT SUBJECTNAME FROM SUBJECTTABLE
SELECT STUDENTNAME FROM MAINTABLE WHERE COURSE = 'BCA' AND STUDENTNAME LIKE 'A%'
SELECT * FROM SEARCHENGINE 
select REGNO from MAINTABLE where COURSE ='BCA' and YEAROFSTUDY = '2014' and STUDENTNAME like 'vishnu%'
DELETE PERSONALTABLE WHERE REGNO=12119744

INSERT INTO PROGRAMME VALUES('--Select--')
INSERT INTO PROGRAMME VALUES('BA')
INSERT INTO PROGRAMME VALUES('BBA')
INSERT INTO PROGRAMME VALUES('BCOM')
INSERT INTO PROGRAMME VALUES('BCA')
INSERT INTO PROGRAMME VALUES('Bsc.Electronics')
INSERT INTO PROGRAMME VALUES('Msc.Computer')
INSERT INTO PROGRAMME VALUES('Msc.Electronics')
INSERT INTO PROGRAMME VALUES('Other')

INSERT INTO RELIGION VALUES('--Select--')
INSERT INTO RELIGION VALUES('CHRISTIAN')
INSERT INTO RELIGION VALUES('HINDU')
INSERT INTO RELIGION VALUES('ISLAM')
INSERT INTO RELIGION VALUES('MUSLIM')
INSERT INTO RELIGION VALUES('Other')

INSERT INTO CASTE VALUES('--Select--')
INSERT INTO CASTE VALUES('Forward Caste')
INSERT INTO CASTE VALUES('Ezhava')
INSERT INTO CASTE VALUES('Thiyya')
INSERT INTO CASTE VALUES('Billiva')
INSERT INTO CASTE VALUES('Viswakarma')
INSERT INTO CASTE VALUES('Dheevara')
INSERT INTO CASTE VALUES('Nadar')
INSERT INTO CASTE VALUES('Backward Castes A-C')
INSERT INTO CASTE VALUES('Backward Castes D-J')
INSERT INTO CASTE VALUES('Backward Castes K')
INSERT INTO CASTE VALUES('Backward Castes M-O')
INSERT INTO CASTE VALUES('Backward Castes P-R')
INSERT INTO CASTE VALUES('Backward Castes S-Y')
INSERT INTO CASTE VALUES('Latin Catholicos')
INSERT INTO CASTE VALUES('Anglo Indians')
INSERT INTO CASTE VALUES('Siuc')
INSERT INTO CASTE VALUES('Converted A-G')
INSERT INTO CASTE VALUES('Converted H-K')
INSERT INTO CASTE VALUES('Converted L-N')
INSERT INTO CASTE VALUES('Converted O-R')
INSERT INTO CASTE VALUES('Converted S-Z')
INSERT INTO CASTE VALUES('Muslim')
INSERT INTO CASTE VALUES('Mappila')
INSERT INTO CASTE VALUES('Other')

INSERT INTO SCHOOL VALUES('--Select--')
INSERT INTO SCHOOL VALUES('St.George HSS Kothamangalam')
INSERT INTO SCHOOL VALUES('Mar Basil HSS Kothamangalam')
INSERT INTO SCHOOL VALUES('St.Peters HSS Pothanikad')
INSERT INTO SCHOOL VALUES('Others')

INSERT INTO SISSETTINS VALUS()

INSERT INTO SEARCHENGINE VALUES(1,'SELECT STUDENTNAME FROM MAINTABLE WHERE COURSE = ''BCA'' AND STUDENTNAME LIKE ''A%''','NAME OF STUDENT STARTING WITH A WHO STUDENIED IN BCA')
INSERT INTO MAINTABLE VALUES(12119744,'VISHNU','BCA',2014)
INSERT INTO MAINTABLE VALUES(12114444,'VISHNU','BCA',2014)
INSERT INTO PERSONALTABLE VALUES(12119744,'VISHNU',2014,'BCA','M','HINDU','EZHAVA','A+',25000,'12-16-1994','AVANAMKOTTU,ENANALLOOR PO,KAKKATTOOR','9961907453')
INSERT INTO FAMILYTABLE VALUES(12119744,'SIVAN AK','COOLIE','AVANAMKOTTU,ENANALLOOR PO,KAKKATTOOR','PADMINI SIVAN','COOLIE',9961907453,'SIVAN AK','COOLIE',9961907453,'NOTING')
INSERT INTO EXAMTABLE VALUES(12119744,397078,'SSLC',2018,'ST JHONS PULINTHANAM','A+',89,2)
INSERT INTO PHYSICALTABLE VALUES(12119744,'CRICKET','NOTHING')
INSERT INTO INTERNALMARKTABLE VALUES(1,12119744,1,'C++','BCA',12,12,78,12,34)
INSERT INTO INTERNALMARKTABLE VALUES(2,12119744,3,'C++','BCA',12,12,78,12,34)
INSERT INTO INTERNALMARKTABLE VALUES(3,12119742,4,'C++','BCA',12,12,78,12,34)
INSERT INTO INTERNALMARKTABLE VALUES(4,12119721,1,'C++','BCA',12,12,78,12,34)
INSERT INTO INTERNALMARKTABLE VALUES(5,12119753,1,'C++','BCA',12,12,78,12,34)
INSERT INTO INTERNALMARKTABLE VALUES(6,12119730,1,'C++','BCA',12,12,78,12,34)

INSERT INTO LOGINTABLE VALUES('ADMIN','W','Yes, There is a Chance')
INSERT INTO LOGINTABLE VALUES('STUDENT','S','A letter of Student')
INSERT INTO LOGINTABLE VALUES('USER',' ','Anything can be Null')

INSERT INTO SUBJECTTABLE VALUES(1,'Communication Skills in English','BA',1,4)
INSERT INTO SUBJECTTABLE VALUES(2,'Common Second Language 1','BA',1,4)
INSERT INTO SUBJECTTABLE VALUES(3,'Methodology of Humanities and Literature','BA',1,4)
INSERT INTO SUBJECTTABLE VALUES(4,'Constitutional Law','BA',1,4)
INSERT INTO SUBJECTTABLE VALUES(5,'Introduction to Mass Communication','BA',1,4)
INSERT INTO SUBJECTTABLE VALUES(6,'Critical Thinking, Academic Writing & Presenation','BA',2,4)
INSERT INTO SUBJECTTABLE VALUES(7,'Common Second Language 2','BA',2,4)
INSERT INTO SUBJECTTABLE VALUES(8,'Introductio to the Study of Language & Literature','BA',2,4)
INSERT INTO SUBJECTTABLE VALUES(9,'Media Law','BA',2,4)
INSERT INTO SUBJECTTABLE VALUES(10,'History of Development of Journalism','BA',2,4)
INSERT INTO SUBJECTTABLE VALUES(11,'Reflections on Indian Polity','BA',3,4)
INSERT INTO SUBJECTTABLE VALUES(12,'Literature and Infomatics','BA',3,4)
INSERT INTO SUBJECTTABLE VALUES(13,'Reading Prose','BA',3,4)
INSERT INTO SUBJECTTABLE VALUES(14,'News Reporting','BA',3,4)
INSERT INTO SUBJECTTABLE VALUES(15,'News Editing','BA',3,4)
INSERT INTO SUBJECTTABLE VALUES(16,'Evolution of Philosophy of Science','BA',4,4)
INSERT INTO SUBJECTTABLE VALUES(17,'Reading Poetry','BA',4,4)
INSERT INTO SUBJECTTABLE VALUES(18,'Reading Fiction','BA',4,4)
INSERT INTO SUBJECTTABLE VALUES(19,'Media Management','BA',4,4)
INSERT INTO SUBJECTTABLE VALUES(20,'Public Relations and Advertising','BA',4,4)
INSERT INTO SUBJECTTABLE VALUES(21,'Reading Drama','BA',5,4)
INSERT INTO SUBJECTTABLE VALUES(22,'Language and Liguistics','BA',5,4)
INSERT INTO SUBJECTTABLE VALUES(23,'Literary Criticism','BA',5,4)
INSERT INTO SUBJECTTABLE VALUES(24,'Postcolonial Literatures','BA',5,4)
INSERT INTO SUBJECTTABLE VALUES(25,'Open Course','BA',5,4)
INSERT INTO SUBJECTTABLE VALUES(26,'Womens Literature','BA',6,4)
INSERT INTO SUBJECTTABLE VALUES(27,'Indian Writing','BA',6,4)
INSERT INTO SUBJECTTABLE VALUES(28,'Comparative Literature','BA',6,4)
INSERT INTO SUBJECTTABLE VALUES(29,'American Literature','BA',6,4)
INSERT INTO SUBJECTTABLE VALUES(30,'Open Course','BA',6,2)
INSERT INTO SUBJECTTABLE VALUES(31,'On the job Training Project','BA',6,2)
INSERT INTO SUBJECTTABLE VALUES(32,'English I','BBA',1,4)
INSERT INTO SUBJECTTABLE VALUES(33,'Historical Perspective of Management','BBA',1,4)
INSERT INTO SUBJECTTABLE VALUES(34,'Global Business Environment','BBA',1,4)
INSERT INTO SUBJECTTABLE VALUES(35,'Fundamentals of Business Mathematics','BBA',1,3)
INSERT INTO SUBJECTTABLE VALUES(36,'Fundamentals of Business Statistics','BBA',1,3)
INSERT INTO SUBJECTTABLE VALUES(37,'Business Accounting','BBA',1,3)
INSERT INTO SUBJECTTABLE VALUES(38,'English II','BBA',2,4)
INSERT INTO SUBJECTTABLE VALUES(39,'Business Ethics and the Indian Social System','BBA',2,3)
INSERT INTO SUBJECTTABLE VALUES(40,'Indian Constitution, Secular State','BBA',2,4)
INSERT INTO SUBJECTTABLE VALUES(41,'Mathematics of Management','BBA',2,3)
INSERT INTO SUBJECTTABLE VALUES(42,'Statistics of Research','BBA',2,3)
INSERT INTO SUBJECTTABLE VALUES(43,'Principles of Management','BBA',2,4)
INSERT INTO SUBJECTTABLE VALUES(44,'Business Communication','BBA',3,3)
INSERT INTO SUBJECTTABLE VALUES(45,'Entrepreneurship','BBA',3,4)
INSERT INTO SUBJECTTABLE VALUES(46,'Business Laws','BBA',3,4)
INSERT INTO SUBJECTTABLE VALUES(47,'research Methodology','BBA',3,4)
INSERT INTO SUBJECTTABLE VALUES(48,'Coporate Accounting','BBA',3,4)
INSERT INTO SUBJECTTABLE VALUES(49,'Infomatics of Management','BBA',4,4)
INSERT INTO SUBJECTTABLE VALUES(50,'Cost Accounting','BBA',4,4)
INSERT INTO SUBJECTTABLE VALUES(51,'Corporate and Industrial Laws','BBA',4,3)
INSERT INTO SUBJECTTABLE VALUES(52,'Managerial Economics','BBA',4,4)
INSERT INTO SUBJECTTABLE VALUES(53,'Marketing Management','BBA',4,4)
INSERT INTO SUBJECTTABLE VALUES(54,'Management Accounting','BBA',5,4)
INSERT INTO SUBJECTTABLE VALUES(55,'Financial Management','BBA',5,4)
INSERT INTO SUBJECTTABLE VALUES(56,'Organizational Behavior','BBA',5,4)
INSERT INTO SUBJECTTABLE VALUES(57,'Human Resource Management','BBA',5,4)
INSERT INTO SUBJECTTABLE VALUES(58,'Investment and Protfolio Management','BBA',5,4)
INSERT INTO SUBJECTTABLE VALUES(59,'Production Management','BBA',6,2)
INSERT INTO SUBJECTTABLE VALUES(60,'Industrial Relations','BBA',6,2)
INSERT INTO SUBJECTTABLE VALUES(61,'Banking and Insurance','BBA',6,4)
INSERT INTO SUBJECTTABLE VALUES(62,'Advertising & Salesmanship','BBA',6,4)
INSERT INTO SUBJECTTABLE VALUES(63,'Income Tax Law & Practice','BBA',6,4)
INSERT INTO SUBJECTTABLE VALUES(64,'Project Work','BBA',6,4)
INSERT INTO SUBJECTTABLE VALUES(65,'English I','BCA',1,4)
INSERT INTO SUBJECTTABLE VALUES(66,'Mathematics','BCA',1,4)
INSERT INTO SUBJECTTABLE VALUES(67,'Statistics','BCA',1,4)
INSERT INTO SUBJECTTABLE VALUES(68,'Introduction to Computers','BCA',1,4)
INSERT INTO SUBJECTTABLE VALUES(69,'Methodology of Programming','BCA',1,3)
INSERT INTO SUBJECTTABLE VALUES(70,'Software Lab I','BCA',1,2)
INSERT INTO SUBJECTTABLE VALUES(71,'English II','BCA',2,4)
INSERT INTO SUBJECTTABLE VALUES(72,'Discrete Mathematics','BCA',2,4)
INSERT INTO SUBJECTTABLE VALUES(73,'Accounting & Programming in Cobol','BCA',2,3)
INSERT INTO SUBJECTTABLE VALUES(74,'Data Structures','BCA',2,3)
INSERT INTO SUBJECTTABLE VALUES(75,'Fundamentals of Digital Systems','BCA',2,4)
INSERT INTO SUBJECTTABLE VALUES(76,'Software Lab II','BCA',2,2)
INSERT INTO SUBJECTTABLE VALUES(77,'Advanced Statstical Method','BCA',3,4)
INSERT INTO SUBJECTTABLE VALUES(78,'Design and Analysis of Algorithms','BCA',3,4)
INSERT INTO SUBJECTTABLE VALUES(79,'Computer Organization & Architecture','BCA',3,4)
INSERT INTO SUBJECTTABLE VALUES(80,'Computer Graphics','BCA',3,4)
INSERT INTO SUBJECTTABLE VALUES(81,'Object Oreinted Programming & C++','BCA',3,3)
INSERT INTO SUBJECTTABLE VALUES(82,'Software Lab III','BCA',3,2)
INSERT INTO SUBJECTTABLE VALUES(83,'Statistics II','BCA',4,4)
INSERT INTO SUBJECTTABLE VALUES(84,'Microprocessor & PC Hardware','BCA',4,4)
INSERT INTO SUBJECTTABLE VALUES(85,'System Analysis & Design','BCA',4,4)
INSERT INTO SUBJECTTABLE VALUES(86,'Database Management System','BCA',4,4)
INSERT INTO SUBJECTTABLE VALUES(87,'Visual Programming Techniques','BCA',4,3)
INSERT INTO SUBJECTTABLE VALUES(88,'Software Lab IV','BCA',4,2)
INSERT INTO SUBJECTTABLE VALUES(89,'Computer Network','BCA',5,4)
INSERT INTO SUBJECTTABLE VALUES(90,'Operating Systems','BCA',5,4)
INSERT INTO SUBJECTTABLE VALUES(91,'Java Programming','BCA',5,3)
INSERT INTO SUBJECTTABLE VALUES(92,'Open Course','BCA',5,4)
INSERT INTO SUBJECTTABLE VALUES(93,'Software Lab V','BCA',5,2)
INSERT INTO SUBJECTTABLE VALUES(94,'Software Development Lab I (Mini Project)','BCA',5,2)
INSERT INTO SUBJECTTABLE VALUES(95,'Web Technology','BCA',6,4)
INSERT INTO SUBJECTTABLE VALUES(96,'Software Engineering','BCA',6,4)
INSERT INTO SUBJECTTABLE VALUES(97,'Elective - Data Mining','BCA',6,4)
INSERT INTO SUBJECTTABLE VALUES(98,'Seminar','BCA',6,2)
INSERT INTO SUBJECTTABLE VALUES(99,'Software Development Lab II (Main Project)','BCA',6,4)
INSERT INTO SUBJECTTABLE VALUES(100,'English I','BSC',1,4)
INSERT INTO SUBJECTTABLE VALUES(101,'Basics of Electronics','BSC',1,4)
INSERT INTO SUBJECTTABLE VALUES(102,'Basic Electronics Laboratary','BSC',1,4)
INSERT INTO SUBJECTTABLE VALUES(103,'Digital Electronics','BSC',1,4)
INSERT INTO SUBJECTTABLE VALUES(104,'Mathematics (BSC)','BSC',1,3)
INSERT INTO SUBJECTTABLE VALUES(105,'Solid State Physics','BSC',1,3)
INSERT INTO SUBJECTTABLE VALUES(106,'English II','BSC',2,4)
INSERT INTO SUBJECTTABLE VALUES(107,'Electronic Circuits','BSC',2,4)
INSERT INTO SUBJECTTABLE VALUES(108,'Digital Electronics Laboratory','BSC',2,4)
INSERT INTO SUBJECTTABLE VALUES(109,'Network Theory','BSC',2,4)
INSERT INTO SUBJECTTABLE VALUES(110,'Methodology of Science','BSC',2,3)
INSERT INTO SUBJECTTABLE VALUES(111,'Linear Algebra','BSC',2,3)
INSERT INTO SUBJECTTABLE VALUES(112,'Microprocessors','BSC',3,4)
INSERT INTO SUBJECTTABLE VALUES(113,'Analog Circuit Lab','BSC',3,4)
INSERT INTO SUBJECTTABLE VALUES(114,'Electromagnetic Theory','BSC',3,4)
INSERT INTO SUBJECTTABLE VALUES(115,'Analog Communication','BSC',3,4)
INSERT INTO SUBJECTTABLE VALUES(116,'Analog Electronics','BSC',3,4)
INSERT INTO SUBJECTTABLE VALUES(117,'Numerical Methods','BSC',3,3)
INSERT INTO SUBJECTTABLE VALUES(118,'Programming in C','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(119,'Microprocessors Lab','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(120,'Microwave Electronics','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(120,'Optoelectronics','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(121,'Instrumentation Electronics','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(121,'Programming Lab in C','BSC',4,4)
INSERT INTO SUBJECTTABLE VALUES(122,'Microcontroller and Embedded Systems','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(123,'Microcontroller Lab','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(124,'Digital Communication','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(125,'Communication Lab','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(126,'Computer Hardware','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(127,'Open Course','BSC',5,4)
INSERT INTO SUBJECTTABLE VALUES(128,'Digital Signal Processing','BSC',6,4)
INSERT INTO SUBJECTTABLE VALUES(129,'Computer Networks','BSC',6,4)
INSERT INTO SUBJECTTABLE VALUES(130,'Radio & Fiber Optics Communication','BSC',6,4)
INSERT INTO SUBJECTTABLE VALUES(131,'Computer Assembling ','BSC',6,4)
INSERT INTO SUBJECTTABLE VALUES(132,'Seminar','BSC',6,2)
INSERT INTO SUBJECTTABLE VALUES(133,'Project Lab','BSC',6,4)
INSERT INTO SUBJECTTABLE VALUES(134,'Viva Voce','BSC',6,2)

INSERT INTO SUBJECTTABLE VALUES(135,'Mathematical Foundation of Computer Science','MSCCOMPUTER',1,4)
INSERT INTO SUBJECTTABLE VALUES(136,'Advanced Computer Systems','MSCCOMPUTER',1,4)
INSERT INTO SUBJECTTABLE VALUES(137,'Digital Circuit Fundamentals','MSCCOMPUTER',1,4)
INSERT INTO SUBJECTTABLE VALUES(138,'Object Oriented Programming & C++','MSCCOMPUTER',1,4)
INSERT INTO SUBJECTTABLE VALUES(139,'C++ & Internet Programming Lab','MSCCOMPUTER',1,4)
INSERT INTO SUBJECTTABLE VALUES(140,'Data and File Strutures','MSCCOMPUTER',2,4)
INSERT INTO SUBJECTTABLE VALUES(141,'Computer Networks','MSCCOMPUTER',2,4)
INSERT INTO SUBJECTTABLE VALUES(142,'Operating Systems','MSCCOMPUTER',2,4)
INSERT INTO SUBJECTTABLE VALUES(143,'Computer Graphics','MSCCOMPUTER',2,4)
INSERT INTO SUBJECTTABLE VALUES(144,'DFS and Graphics Lab','MSCCOMPUTER',2,4)
INSERT INTO SUBJECTTABLE VALUES(145,'Relational Database Management Systems','MSCCOMPUTER',3,4)
INSERT INTO SUBJECTTABLE VALUES(146,'java Programming','MSCCOMPUTER',3,4)
INSERT INTO SUBJECTTABLE VALUES(147,'Computer Networks','MSCCOMPUTER',3,4)
INSERT INTO SUBJECTTABLE VALUES(148,'Software Engineering','MSCCOMPUTER',3,4)
INSERT INTO SUBJECTTABLE VALUES(149,'Java and Oracle Lab','MSCCOMPUTER',3,4)
INSERT INTO SUBJECTTABLE VALUES(150,'Visual Basic.Net','MSCCOMPUTER',4,41)
INSERT INTO SUBJECTTABLE VALUES(151,'SQL Server','MSCCOMPUTER',4,41)
INSERT INTO SUBJECTTABLE VALUES(152,'Project','MSCCOMPUTER',4,41)
INSERT INTO SUBJECTTABLE VALUES(153,'Seminar','MSCCOMPUTER',4,41)
INSERT INTO SUBJECTTABLE VALUES(154,'Viva Voce','MSCCOMPUTER',4,41)
INSERT INTO SUBJECTTABLE VALUES(155,'Advanced Java Programming','MSCCOMPUTER',4,42)
INSERT INTO SUBJECTTABLE VALUES(156,'Linux & Web Programming using PHP','MSCCOMPUTER',4,42)
INSERT INTO SUBJECTTABLE VALUES(157,'Project ','MSCCOMPUTER',4,42)
INSERT INTO SUBJECTTABLE VALUES(158,'Seminar','MSCCOMPUTER',4,42)
INSERT INTO SUBJECTTABLE VALUES(159,'Viva Voce','MSCCOMPUTER',4,42)
INSERT INTO SUBJECTTABLE VALUES(160,'Assembly Language programming','MSCCOMPUTER',4,43)
INSERT INTO SUBJECTTABLE VALUES(161,'Visual C++','MSCCOMPUTER',4,43)
INSERT INTO SUBJECTTABLE VALUES(162,'Project','MSCCOMPUTER',4,43)
INSERT INTO SUBJECTTABLE VALUES(163,'Seminar','MSCCOMPUTER',4,43)
INSERT INTO SUBJECTTABLE VALUES(164,'Viva Voce','MSCCOMPUTER',4,43)

INSERT INTO SUBJECTTABLE VALUES(165,'Electronic Device & Circuit Design','MSCELECTRONICS',1,4)
INSERT INTO SUBJECTTABLE VALUES(166,'Modern Communication Systems','MSCELECTRONICS',1,4)
INSERT INTO SUBJECTTABLE VALUES(167,'Advanced Network & Systems','MSCELECTRONICS',1,4)
INSERT INTO SUBJECTTABLE VALUES(168,'MEMS and Power Electronics','MSCELECTRONICS',1,4)
INSERT INTO SUBJECTTABLE VALUES(169,'Advanced Electronics Lab','MSCELECTRONICS',1,4)
INSERT INTO SUBJECTTABLE VALUES(170,'Microprocessor & Interfacing Techniques','MSCELECTRONICS',2,4)
INSERT INTO SUBJECTTABLE VALUES(171,'Robotics','MSCELECTRONICS',2,4)
INSERT INTO SUBJECTTABLE VALUES(172,'VLSI Design & Analysis','MSCELECTRONICS',2,4)
INSERT INTO SUBJECTTABLE VALUES(173,'Power Electronics','MSCELECTRONICS',2,4)
INSERT INTO SUBJECTTABLE VALUES(174,'Advanced Electronics Lab','MSCELECTRONICS',2,4)
INSERT INTO SUBJECTTABLE VALUES(175,'Fiber Optics & Applications','MSCELECTRONICS',3,4)
INSERT INTO SUBJECTTABLE VALUES(176,'Programming in C++','MSCELECTRONICS',3,4)
INSERT INTO SUBJECTTABLE VALUES(177,'Data Communication Networks I','MSCELECTRONICS',3,4)
INSERT INTO SUBJECTTABLE VALUES(178,'Internet Technology & Programming','MSCELECTRONICS',3,4)
INSERT INTO SUBJECTTABLE VALUES(179,'C++ Programming Language Lab','MSCELECTRONICS',3,4)
INSERT INTO SUBJECTTABLE VALUES(180,'Control Systems','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(181,'Microcontroller & Applications','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(182,'PC Hardware','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(183,'PC Trouble Shooting Lab','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(184,'Seminar','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(185,'Project','MSCELECTRONICS',4,4)
INSERT INTO SUBJECTTABLE VALUES(186,'Viva Voce','MSCELECTRONICS',4,4)

UPDATE LOGINTABLE SET PWD =' ' WHERE USERNAME='USER'

SELECT * FROM LOGINTABLE 
select * from SUBJECTTABLE where course = 'ba' and sem = 1
select * from SUBJECTTABLE where course = 'ba' and sem = 2
select * from SUBJECTTABLE where course = 'ba' and sem = 3
select * from SUBJECTTABLE where course = 'ba' and sem = 4
select * from SUBJECTTABLE where course = 'ba' and sem = 5
select * from SUBJECTTABLE where course = 'ba' and sem = 6

select * from SUBJECTTABLE where course = 'bba' and sem = 1
select * from SUBJECTTABLE where course = 'bba' and sem = 2
select * from SUBJECTTABLE where course = 'bba' and sem = 3
select * from SUBJECTTABLE where course = 'bba' and sem = 4
select * from SUBJECTTABLE where course = 'bba' and sem = 5
select * from SUBJECTTABLE where course = 'bba' and sem = 6

select * from SUBJECTTABLE where course = 'bca' and sem = 1
select * from SUBJECTTABLE where course = 'bca' and sem = 2
select * from SUBJECTTABLE where course = 'bca' and sem = 3
select * from SUBJECTTABLE where course = 'bca' and sem = 4
select * from SUBJECTTABLE where course = 'bca' and sem = 5
select * from SUBJECTTABLE where course = 'bca' and sem = 6

select * from SUBJECTTABLE where course = 'bsc' and sem = 1
select * from SUBJECTTABLE where course = 'bsc' and sem = 2
select * from SUBJECTTABLE where course = 'bsc' and sem = 3
select * from SUBJECTTABLE where course = 'bsc' and sem = 4
select * from SUBJECTTABLE where course = 'bsc' and sem = 5
select * from SUBJECTTABLE where course = 'bsc' and sem = 6

select * from SUBJECTTABLE where course = 'msccomputer' and sem = 1
select * from SUBJECTTABLE where course = 'msccomputer' and sem = 2
select * from SUBJECTTABLE where course = 'msccomputer' and sem = 3
select * from SUBJECTTABLE where course = 'msccomputer' and sem = 4

select * from SUBJECTTABLE where course = 'mscelectronics' and sem = 1
select * from SUBJECTTABLE where course = 'mscelectronics' and sem = 2
select * from SUBJECTTABLE where course = 'mscelectronics' and sem = 3
select * from SUBJECTTABLE where course = 'mscelectronics' and sem = 4

delete from SUBJECTTABLE where subjectid=155
select * from MAINTABLE 